FROM alpine/git as cloner
WORKDIR /opt
RUN git clone https://github.com/code4romania/legal-consultation-client

FROM node:12.7-alpine
RUN \
  echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
  && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
  && apk --no-cache  update \
  && apk --no-cache  upgrade \
  && apk add --no-cache --virtual .build-deps \
  gifsicle pngquant optipng libjpeg-turbo-utils \
  udev ttf-opensans chromium \
  && rm -rf /var/cache/apk/* /tmp/*
ENV CHROME_BIN /usr/bin/chromium-browser

COPY --from=cloner /opt /opt
WORKDIR /opt/legal-consultation-client
RUN npm install
RUN npm run test
