FROM alpine/git as cloner
WORKDIR /opt
RUN git clone https://github.com/code4romania/legal-consultation-client

FROM node:12.7-alpine as builder
COPY --from=cloner /opt /opt
WORKDIR /opt/legal-consultation-client
RUN npm install
RUN npm run build --prod

FROM nginx:1.17-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /opt/legal-consultation-client/dist/legal-consultation-client /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
